[package]
name = "tzf-wasm"
version = "0.1.4"
edition = "2021"
description = "A wasm library for tzf-rs"
repository = "https://github.com/ringsaturn/tzf-wasm"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
tzf-rs = { version = "0.4.9", default-features = false }
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
