[package]
name = "tzf-wasm"
version = "0.1.1"
edition = "2021"
description = "A wasm library for tzf-rs"
repository = "https://github.com/ringsaturn/tzf-wasm"
license = "MIT"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
tzf-rs = { version = "0.4.8", default-features = false }
wasm-bindgen = "0.2.84"
getrandom = { version = "*", features = ["js"]}
