name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  deployments: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # - uses: jetli/wasm-pack-action@v0.4.0
      #   with:
      #     version: "latest"
      - run: make build
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   if: ${{ github.ref_name == 'main' }}
      #   with:
      #     path: "./dist"

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   if: ${{ github.ref_name == 'main' }}
      #   uses: actions/deploy-pages@v4
